= Conclusion <conclusion>

This thesis set out to modernise ICNML and to make it reliable and understandable, a platform that held genuine biometric data yet ran on an end-of-life language, could not be rebuilt from its own sources, and whose security no one had written down. Measured against the four objectives fixed at the start in the specifications, the work delivered on all of them, and on two it went beyond documentation into engineering.

== What was achieved

On maintainability, ICNML moved from having no documentation at all to a complete account of the system, its interface, its codebase, and a development environment a new contributor can actually bring up. The decisive step here was the migration of the entire codebase, four internal libraries and the Flask application, from Python 2.7 to Python 3.11 (@python3-migration). This removed the root cause behind most of the platform's fragility, and it was done without a data migration, because every stored format was preserved byte-for-byte so that existing accounts and encrypted images remain valid.

On security transparency, every core mechanism is now documented in plain terms with its weaknesses named rather than hidden. The audit produced concrete, actionable findings, among them the use of a predictable random source where a cryptographic one is required, timing-unsafe secret comparisons, a hand-rolled padding construction in place of authenticated encryption, image endpoints that serve unmarked copies and so leave no audit trail, and the fact that a donor's "erasure" is only eventual, because the per-donor keys are included in backups and so survive until the retention window passes (@per-donor-security, @crypto-utils, @backup-security). Naming these honestly is itself a result, since a weakness that is written down can be fixed, whereas one that is undocumented cannot.

On the management operations, the platform's original deployment pipeline is documented (@deployment), and the modernised system has been made runnable again end to end, both as a convenient local stack and as a production-faithful deployment with its full two-factor and passkey security genuinely working (@running-icnml).

On the user experience, a set of practical features was delivered, and, going well beyond the brief, the crude barcode stamp that the platform used to mark downloads, removable by a single crop, was replaced with a robust invisible watermark that spreads a cryptographic identifier across the whole image. That scheme was not merely described but designed, implemented, and measured against a battery of attacks, and the retained variant recovers the recipient from the great majority of attacked copies while remaining essentially invisible (@state-of-the-art, @watermark-implementation, @ux-improvements).

== Limitations

Several boundaries of this work should be stated plainly. The security weaknesses uncovered were deliberately documented rather than fixed during the migration, on the principle that a language port and a security change should not be tangled together in the same step, so they remain as prioritised follow-up work. The original automated deployment pipeline is still inert, and production has not yet been re-established on the new stack, the single-box deployment shown here demonstrates feasibility but is not a full replacement. Finally the traceable watermark is scoped to a single redistributing recipient, it does not defend against several recipients comparing their differently-marked copies to erase the trace.

== Future work

Each chapter closed with an assessment, and the improvements those assessments identified but this thesis did not carry out are collected here as a single roadmap, ordered roughly from the most security- and data-critical downward. Most are isolated, well-defined changes rather than architectural ones.

The cryptographic core comes first, because every security process depends on it. The non-cryptographic `random` module should be replaced by the `secrets` module over a full-byte alphabet everywhere it feeds a secret, the `SECRET_KEY`, the salts, the DEK salt, and the password-reset tokens (@crypto-utils). The hand-rolled `"icnml$"` integrity marker and the error-swallowing CBC decryption should give way to authenticated encryption such as AES-GCM (@crypto-utils). The hardcoded `"AES256"` salt on the session password should become a random one, the reset endpoints should be rate-limited, and the rate-limit key should be narrowed from a `/16` block to the individual address to stop collateral lockouts (@roles-and-permissions).

Key management and data-at-rest bound the damage a database breach could do. The DEKs are stored in the same database as the images they decrypt, so a single dump exposes everything, and they should be separated from the encrypted data (@per-donor-security). The `cnm_candidate` images that presently escape per-donor encryption should be brought back under it (@biometric-data). Images held as base64 text should be stored as raw bytes, removing roughly a third of avoidable bloat and, ideally, served from a dedicated directory rather than the database (@biometric-data). And the application's private GPG key, needed to decrypt the consent forms and not yet located, must be recovered, without it those forms cannot be read (@per-donor-security).

Erasure and deletion should be made consistent with the right to erasure the platform promises. Because the DEKs are included in the backups, a donor's deletion only takes full effect after the thirty-day retention window, and closing that window would make erasure immediate (@per-donor-security, @backup-security). Biometric deletion is a hard `DELETE` with no soft-delete or audit trail, unlike the reversible mechanism used elsewhere, and the consent-form restriction on submission deletion contradicts the DEK-based erasure, so the two paths should be aligned (@biometric-data). The duplicate-e-mail check should also span every submission rather than only the current submitter's (@per-donor-security).

The backups themselves need to be thought out differently in regards to the decision of where to store the DEKs and images. The legacy setup is not suitable for these changes.

Deployment and maintainability are the path back to a shippable system. The original automated pipeline is inert and built on now-archived tooling, so a production deployment should be re-established around the Python 3.11 stack on maintained, submodule-free tooling (@deployment, @running-icnml). The missing submodule dependencies should be restored or vendored and the unused repositories retired (@repo-struct), and the multi-thousand-line `__init__.py` modules broken up. Several smaller code-clarity items belong here too, un-hardcoding the consent-form GPG key, renaming the misleading `email` parameter in the key-derivation code that in fact holds an e-mail hash, and documenting the reconstruction paths that are the easiest part of the per-donor mechanism to misread (@per-donor-security, @roles-and-permissions).

Finally, the traceability work can be extended. The watermark should be applied on every image-serving route, including the preview and full-resolution endpoints that currently serve unmarked copies and so leave a gap in the audit trail (@tattooing, @watermark-implementation). The remaining interface gaps, the inert controls, the unexplained status badges, and the PiAnoS gateway error, are lower-priority but well-defined items (@application-overview).

== Closing

ICNML is now a platform that can be explained, rebuilt, and safely worked on, which was not the case when this work began. It runs on a supported language, its security is documented rather than assumed, its downloads carry a payload that survives ordinary tampering, and the next contributor inherits both a working environment and a clear, honest map of what still needs strengthening. For a system entrusted with data that a person can never change, being understandable is not a luxury but a precondition for being trustworthy, and moving ICNML towards that standard is the contribution of this thesis.
