#import "../macros.typ": note

= Cryptographic Utilities

This chapter documents the four utility files that are the base of all cryptographic operations in ICNML: `utils/rand.py`, `hash.py`, `utils/aes.py` and `utils/encryption.py`. These files are called from every layer of the application, password storage, donor email protection, biometric file encryption and DEK lifecycle. Their behaviour and limitations have broad impact.

== `utils/rand.py`, Random Data Generation

The salt values, the DEK check payloads or the `SECRET_KEY` fallback, are all random byte generated by a single function:

#figure(
  ```python
    import random
    import string

    def random_data( N ):
        return "".join( random.choice( string.ascii_uppercase + string.digits ) for _ in range( N ) )
  ```,
  caption: [Function `random_data` (`utils/rand.py`, ln 7-12)]
)

The function creates from 36 character alphabet (26 uppercase letters + 10 digits) using Python's built-in `random` module. However, `random` is a Mersenne Twister PRNG designed for statistical simulations, not cryptography. Its internal state can be reconstructed from enough outputs. 

#note[Maybe check how many outputs to then predict all future ones]

The correct replacement would be to use the `secrets` module which reads from the OS entropy source (`/dev/urandom` on Linux).

#figure(
    table(
        columns: (auto, auto, 1fr),
        stroke: 0.5pt,
        fill: (col, row) => if row == 0 { luma(220) } else { white },
        align: (left, center, left),
        table.header[Call site][Length (N)][Purpose],
        [`config.py:23`],   [20], [Flask `SECRET_KEY` fallback when env var is absent],
        [`utils/hash.py:43`],  [100], [Default PBKDF2 salt when none is supplied],
        [`utils/encryption.py:183`], [20], [DEK salt (`DEK_SALT_LENGTH`)],
        [`utils/encryption.py:194`], [20], [Random data inside the DEK check object],
        [`views/newuser/__init__.py`], [20], [Password salt (`PASSWORD_SALT_LENGTH`)],
    ),
    caption: [Sites that call `random_data`]
)

The alphabet restriction also reduces entropy below what the length suggests. A 20 character string from this alphabet carries only $20 times log_2(36) approx 103$ bits rather than $20 times 8 = 160$ bits from a full-byte source @entropy-wiki.

== `utils/hash.py`, PBKDF2 Wrapper

All hashing in the application goes through the `pbkdf2` class, which wraps `hashlib.pbkdf2_hmac`. 

=== Construction and hash format 

The class accepts a word, an optional salt, an iteration count and a hash name. When no salt is provided, it generates one via `rand.random_data(100)`.

#figure(
  ```python
  def __init__( self, word, salt = None, iterations = 20000, hash_name = "sha512" ):
      if salt != None and salt.startswith( "pbkdf2$" ):
          self.word = word
          self.stored_hash = salt
          _, self.hash_name, self.salt, self.iterations, self.h = salt.split( "$" )
          self.iterations = int( self.iterations )
      
      else:
          self.word = word
          self.salt = salt or rand.random_data( 100 )
          self.iterations = int( iterations )
          self.hash_name = hash_name
          self.stored_hash = None
          self.h = None
  ```,
  caption: [Constructor (`utils/hash.py`, ln 34-47)]
)

The constructor doubles as a parser: if `salt` starts with `"pbkdf2$"`, the argument is treated as a stored hash string and decomposed. This allows the same object to be used both for hashing and for verification.

The `hash()` method produces either the raw hex digest or a self-describing stored string:

#figure(
    ```python
    def hash( self, hash_only = False ):
        h = hashlib.pbkdf2_hmac( self.hash_name, self.word, self.salt, self.iterations )
        h = binascii.hexlify( h )
        if hash_only:
            return h
        else:
            return "$".join( map( str, [ "pbkdf2", self.hash_name, self.salt, self.iterations, h ] ) )
    ```,
    caption: [Hash output (`utils/hash.py`, ln 49-62)]
)

The stored format `pbkdf2$sha512$<salt>$<iterations>$<hex_digest>` is self-describing. The application uses the iteration count stored in the hash to detect outdated hashes and rehash them on the next login. The iteration counts configured in `config.py` are:

#figure(
    table(
      columns: (auto, auto, auto),
      stroke: 0.5pt,
      fill: (col, row) => if row == 0 { luma(220) } else { white },
      align: (left, center, left),
      table.header[Constant][Iterations][Used for],
      [`EMAIL_NB_ITERATIONS`],    [50 000],  [Donor email hash (submissions, users tables)],
      [`PASSWORD_NB_ITERATIONS`], [50 000],  [Server-side password hash (second factor)],
      [`DEK_NB_ITERATIONS`],      [500 000], [Data Encryption Key derivation],
      [`CF_NB_ITERATIONS`],       [100 000], [Email hash in the consent form (`cf`) table],
  ),
  caption: [Iteration counts (`config.py`, ln 27-30)]
)

Note that the `pbkdf2` default of 20000 iterations is only used when the caller does not supply an override. None of the security-critical call rely on the default.

== `utils/aes.py`, AES-256-CBC Wrapper

The `AESCipher` class and its two public wrappers (`do_encrypt`, `do_decrypt`) handle all symmetric encryption in the application.

=== Key derivation

The class derives the AES key by hashing the input password with SHA-256:

#figure(
    ```python
    class AESCipher( object ):
        def __init__( self, key ):
            self.key = hashlib.sha256( key.encode() ).digest()
    ```,
    caption: [Key derivation (`utils/aes.py`, ln 67-68)]
)

SHA-256 produces a 32-byte key suitable for AES-256. When the caller passes a PBKDF2 output as the key, which is the case for DEK-based encryption and session-scoped encryption, this second SHA-256 hash compresses the input.

=== Ciphertext format

Encryption generates a random IV from Cryptography's `Random.new()`, runs AES in CBC mode, and encodes the result as a `$` delimited ASCII string:

#figure(
    ```python
    def encrypt( self, data ):
        data = self._pad( data )
        iv = Random.new().read( AES.block_size )
        cipher = AES.new( self.key, AES.MODE_CBC, iv )
        iv = base64.b64encode( iv )
        encrypted = base64.b64encode( cipher.encrypt( data ) )
        return "$".join( map( str, [ "AES256", iv, encrypted ] ) )
    ```,
    caption: [Encryption (`utils/aes.py`, ln 70-88)]
)

The stored ciphertext format is `AES256$<base64 IV>$<base64 ciphertext>`. The IV is unique per encryption call. 

Decryption splits on `$` decodes both fields and reconstructs the cipher:

#figure(
    ```python
    def decrypt( self, data ):
        _, iv, data = data.split( "$" )
        iv = base64.b64decode( iv )
        data = base64.b64decode( data )
        cipher = AES.new( self.key, AES.MODE_CBC, iv )
        return self._unpad( cipher.decrypt( data ) ).decode( "utf-8" )
    ```,
    caption: [Decryption (`utils/aes.py`, ln 90-104)]
)

